/*
 * OPN2 Bank Editor by Wohlstand, a free tool for music bank editing
 * Copyright (c) 2017-2023 Vitaly Novichkov <admin@wohlnet.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "ins_names.h"

static const struct MidiProgram Gm1Set[] =
{
    {'M',   0,   0,   0, "GM1 Melodic", "Acoustic Grand Piano"},
    {'M',   0,   0,   1, "GM1 Melodic", "Bright Acoustic Piano"},
    {'M',   0,   0,   2, "GM1 Melodic", "Electric Grand Piano"},
    {'M',   0,   0,   3, "GM1 Melodic", "Honky-tonk Piano"},
    {'M',   0,   0,   4, "GM1 Melodic", "Electric Piano 1"},
    {'M',   0,   0,   5, "GM1 Melodic", "Electric Piano 2"},
    {'M',   0,   0,   6, "GM1 Melodic", "Harpsichord"},
    {'M',   0,   0,   7, "GM1 Melodic", "Clavi"},
    {'M',   0,   0,   8, "GM1 Melodic", "Celesta"},
    {'M',   0,   0,   9, "GM1 Melodic", "Glockenspiel"},
    {'M',   0,   0,  10, "GM1 Melodic", "Music Box"},
    {'M',   0,   0,  11, "GM1 Melodic", "Vibraphone"},
    {'M',   0,   0,  12, "GM1 Melodic", "Marimba"},
    {'M',   0,   0,  13, "GM1 Melodic", "Xylophone"},
    {'M',   0,   0,  14, "GM1 Melodic", "Tubular Bells"},
    {'M',   0,   0,  15, "GM1 Melodic", "Dulcimer"},
    {'M',   0,   0,  16, "GM1 Melodic", "Drawbar Organ"},
    {'M',   0,   0,  17, "GM1 Melodic", "Percussive Organ"},
    {'M',   0,   0,  18, "GM1 Melodic", "Rock Organ"},
    {'M',   0,   0,  19, "GM1 Melodic", "Church Organ"},
    {'M',   0,   0,  20, "GM1 Melodic", "Reed Organ"},
    {'M',   0,   0,  21, "GM1 Melodic", "Accordion"},
    {'M',   0,   0,  22, "GM1 Melodic", "Harmonica"},
    {'M',   0,   0,  23, "GM1 Melodic", "Tango Accordion"},
    {'M',   0,   0,  24, "GM1 Melodic", "Acoustic Guitar (nylon)"},
    {'M',   0,   0,  25, "GM1 Melodic", "Acoustic Guitar (steel)"},
    {'M',   0,   0,  26, "GM1 Melodic", "Electric Guitar (jazz)"},
    {'M',   0,   0,  27, "GM1 Melodic", "Electric Guitar (clean)"},
    {'M',   0,   0,  28, "GM1 Melodic", "Electric Guitar (muted)"},
    {'M',   0,   0,  29, "GM1 Melodic", "Overdriven Guitar"},
    {'M',   0,   0,  30, "GM1 Melodic", "Distortion Guitar"},
    {'M',   0,   0,  31, "GM1 Melodic", "Guitar Harmonics"},
    {'M',   0,   0,  32, "GM1 Melodic", "Acoustic Bass"},
    {'M',   0,   0,  33, "GM1 Melodic", "Electric Bass (finger)"},
    {'M',   0,   0,  34, "GM1 Melodic", "Electric Bass (pick)"},
    {'M',   0,   0,  35, "GM1 Melodic", "Fretless Bass"},
    {'M',   0,   0,  36, "GM1 Melodic", "Slap Bass 1"},
    {'M',   0,   0,  37, "GM1 Melodic", "Slap Bass 2"},
    {'M',   0,   0,  38, "GM1 Melodic", "Synth Bass 1"},
    {'M',   0,   0,  39, "GM1 Melodic", "Synth Bass 2"},
    {'M',   0,   0,  40, "GM1 Melodic", "Violin"},
    {'M',   0,   0,  41, "GM1 Melodic", "Viola"},
    {'M',   0,   0,  42, "GM1 Melodic", "Cello"},
    {'M',   0,   0,  43, "GM1 Melodic", "Contrabass"},
    {'M',   0,   0,  44, "GM1 Melodic", "Tremolo Strings"},
    {'M',   0,   0,  45, "GM1 Melodic", "Pizzicato Strings"},
    {'M',   0,   0,  46, "GM1 Melodic", "Orchestral Harp"},
    {'M',   0,   0,  47, "GM1 Melodic", "Timpani"},
    {'M',   0,   0,  48, "GM1 Melodic", "String Ensembles 1"},
    {'M',   0,   0,  49, "GM1 Melodic", "String Ensembles 2"},
    {'M',   0,   0,  50, "GM1 Melodic", "SynthStrings 1"},
    {'M',   0,   0,  51, "GM1 Melodic", "SynthStrings 2"},
    {'M',   0,   0,  52, "GM1 Melodic", "Choir Aahs"},
    {'M',   0,   0,  53, "GM1 Melodic", "Voice Oohs"},
    {'M',   0,   0,  54, "GM1 Melodic", "Synth Voice"},
    {'M',   0,   0,  55, "GM1 Melodic", "Orchestra Hit"},
    {'M',   0,   0,  56, "GM1 Melodic", "Trumpet"},
    {'M',   0,   0,  57, "GM1 Melodic", "Trombone"},
    {'M',   0,   0,  58, "GM1 Melodic", "Tuba"},
    {'M',   0,   0,  59, "GM1 Melodic", "Muted Trumpet"},
    {'M',   0,   0,  60, "GM1 Melodic", "French Horn"},
    {'M',   0,   0,  61, "GM1 Melodic", "Brass Section"},
    {'M',   0,   0,  62, "GM1 Melodic", "Synth Brass 1"},
    {'M',   0,   0,  63, "GM1 Melodic", "Synth Brass 2"},
    {'M',   0,   0,  64, "GM1 Melodic", "Soprano Sax"},
    {'M',   0,   0,  65, "GM1 Melodic", "Alto Sax"},
    {'M',   0,   0,  66, "GM1 Melodic", "Tenor Sax"},
    {'M',   0,   0,  67, "GM1 Melodic", "Baritone Sax"},
    {'M',   0,   0,  68, "GM1 Melodic", "Oboe"},
    {'M',   0,   0,  69, "GM1 Melodic", "English Horn"},
    {'M',   0,   0,  70, "GM1 Melodic", "Bassoon"},
    {'M',   0,   0,  71, "GM1 Melodic", "Clarinet"},
    {'M',   0,   0,  72, "GM1 Melodic", "Piccolo"},
    {'M',   0,   0,  73, "GM1 Melodic", "Flute"},
    {'M',   0,   0,  74, "GM1 Melodic", "Recorder"},
    {'M',   0,   0,  75, "GM1 Melodic", "Pan Flute"},
    {'M',   0,   0,  76, "GM1 Melodic", "Blown Bottle"},
    {'M',   0,   0,  77, "GM1 Melodic", "Shakuhachi"},
    {'M',   0,   0,  78, "GM1 Melodic", "Whistle"},
    {'M',   0,   0,  79, "GM1 Melodic", "Ocarina"},
    {'M',   0,   0,  80, "GM1 Melodic", "Lead 1 (square)"},
    {'M',   0,   0,  81, "GM1 Melodic", "Lead 2 (sawtooth)"},
    {'M',   0,   0,  82, "GM1 Melodic", "Lead 3 (calliope)"},
    {'M',   0,   0,  83, "GM1 Melodic", "Lead 4 (chiff)"},
    {'M',   0,   0,  84, "GM1 Melodic", "Lead 5 (charang)"},
    {'M',   0,   0,  85, "GM1 Melodic", "Lead 6 (voice)"},
    {'M',   0,   0,  86, "GM1 Melodic", "Lead 7 (fifths)"},
    {'M',   0,   0,  87, "GM1 Melodic", "Lead 8 (bass + lead)"},
    {'M',   0,   0,  88, "GM1 Melodic", "Pad 1 (new age)"},
    {'M',   0,   0,  89, "GM1 Melodic", "Pad 2 (warm)"},
    {'M',   0,   0,  90, "GM1 Melodic", "Pad 3 (polysynth)"},
    {'M',   0,   0,  91, "GM1 Melodic", "Pad 4 (choir)"},
    {'M',   0,   0,  92, "GM1 Melodic", "Pad 5 (bowed)"},
    {'M',   0,   0,  93, "GM1 Melodic", "Pad 6 (metallic)"},
    {'M',   0,   0,  94, "GM1 Melodic", "Pad 7 (halo)"},
    {'M',   0,   0,  95, "GM1 Melodic", "Pad 8 (sweep)"},
    {'M',   0,   0,  96, "GM1 Melodic", "FX 1 (rain)"},
    {'M',   0,   0,  97, "GM1 Melodic", "FX 2 (soundtrack)"},
    {'M',   0,   0,  98, "GM1 Melodic", "FX 3 (crystal)"},
    {'M',   0,   0,  99, "GM1 Melodic", "FX 4 (atmosphere)"},
    {'M',   0,   0, 100, "GM1 Melodic", "FX 5 (brightness)"},
    {'M',   0,   0, 101, "GM1 Melodic", "FX 6 (goblins)"},
    {'M',   0,   0, 102, "GM1 Melodic", "FX 7 (echoes)"},
    {'M',   0,   0, 103, "GM1 Melodic", "FX 8 (sci-fi)"},
    {'M',   0,   0, 104, "GM1 Melodic", "Sitar"},
    {'M',   0,   0, 105, "GM1 Melodic", "Banjo"},
    {'M',   0,   0, 106, "GM1 Melodic", "Shamisen"},
    {'M',   0,   0, 107, "GM1 Melodic", "Koto"},
    {'M',   0,   0, 108, "GM1 Melodic", "Kalimba"},
    {'M',   0,   0, 109, "GM1 Melodic", "Bag pipe"},
    {'M',   0,   0, 110, "GM1 Melodic", "Fiddle"},
    {'M',   0,   0, 111, "GM1 Melodic", "Shanai"},
    {'M',   0,   0, 112, "GM1 Melodic", "Tinkle Bell"},
    {'M',   0,   0, 113, "GM1 Melodic", "Agogo"},
    {'M',   0,   0, 114, "GM1 Melodic", "Steel Drums"},
    {'M',   0,   0, 115, "GM1 Melodic", "Woodblock"},
    {'M',   0,   0, 116, "GM1 Melodic", "Taiko Drum"},
    {'M',   0,   0, 117, "GM1 Melodic", "Melodic Tom"},
    {'M',   0,   0, 118, "GM1 Melodic", "Synth Drum"},
    {'M',   0,   0, 119, "GM1 Melodic", "Reverse Cymbal"},
    {'M',   0,   0, 120, "GM1 Melodic", "Guitar Fret Noise"},
    {'M',   0,   0, 121, "GM1 Melodic", "Breath Noise"},
    {'M',   0,   0, 122, "GM1 Melodic", "Seashore"},
    {'M',   0,   0, 123, "GM1 Melodic", "Bird Tweet"},
    {'M',   0,   0, 124, "GM1 Melodic", "Telephone Ring"},
    {'M',   0,   0, 125, "GM1 Melodic", "Helicopter"},
    {'M',   0,   0, 126, "GM1 Melodic", "Applause"},
    {'M',   0,   0, 127, "GM1 Melodic", "Gunshot"},
    {'P',   0,   0,  35, "GM1 Percussion", "Acoustic Bass Drum"},
    {'P',   0,   0,  36, "GM1 Percussion", "Bass Drum 1"},
    {'P',   0,   0,  37, "GM1 Percussion", "Side Stick"},
    {'P',   0,   0,  38, "GM1 Percussion", "Acoustic Snare"},
    {'P',   0,   0,  39, "GM1 Percussion", "Hand Clap"},
    {'P',   0,   0,  40, "GM1 Percussion", "Electric Snare"},
    {'P',   0,   0,  41, "GM1 Percussion", "Low Floor Tom"},
    {'P',   0,   0,  42, "GM1 Percussion", "Closed Hi-hat"},
    {'P',   0,   0,  43, "GM1 Percussion", "High Floor Tom"},
    {'P',   0,   0,  44, "GM1 Percussion", "Pedal Hi-hat"},
    {'P',   0,   0,  45, "GM1 Percussion", "Low Tom"},
    {'P',   0,   0,  46, "GM1 Percussion", "Open Hi-hat"},
    {'P',   0,   0,  47, "GM1 Percussion", "Low-Mid Tom"},
    {'P',   0,   0,  48, "GM1 Percussion", "High Mid Tom"},
    {'P',   0,   0,  49, "GM1 Percussion", "Crash Cymbal 1"},
    {'P',   0,   0,  50, "GM1 Percussion", "High Tom"},
    {'P',   0,   0,  51, "GM1 Percussion", "Ride Cymbal 1"},
    {'P',   0,   0,  52, "GM1 Percussion", "Chinese Cymbal"},
    {'P',   0,   0,  53, "GM1 Percussion", "Ride Bell"},
    {'P',   0,   0,  54, "GM1 Percussion", "Tambourine"},
    {'P',   0,   0,  55, "GM1 Percussion", "Splash Cymbal"},
    {'P',   0,   0,  56, "GM1 Percussion", "Cowbell"},
    {'P',   0,   0,  57, "GM1 Percussion", "Crash Cymbal 2"},
    {'P',   0,   0,  58, "GM1 Percussion", "Vibra-slap"},
    {'P',   0,   0,  59, "GM1 Percussion", "Ride Cymbal 2"},
    {'P',   0,   0,  60, "GM1 Percussion", "High Bongo"},
    {'P',   0,   0,  61, "GM1 Percussion", "Low Bongo"},
    {'P',   0,   0,  62, "GM1 Percussion", "Mute Hi Conga"},
    {'P',   0,   0,  63, "GM1 Percussion", "Open Hi Conga"},
    {'P',   0,   0,  64, "GM1 Percussion", "Low Conga"},
    {'P',   0,   0,  65, "GM1 Percussion", "High Timbale"},
    {'P',   0,   0,  66, "GM1 Percussion", "Low Timbale"},
    {'P',   0,   0,  67, "GM1 Percussion", "High Agogo"},
    {'P',   0,   0,  68, "GM1 Percussion", "Low Agogo"},
    {'P',   0,   0,  69, "GM1 Percussion", "Cabasa"},
    {'P',   0,   0,  70, "GM1 Percussion", "Maracas"},
    {'P',   0,   0,  71, "GM1 Percussion", "Short Whistle"},
    {'P',   0,   0,  72, "GM1 Percussion", "Long Whistle"},
    {'P',   0,   0,  73, "GM1 Percussion", "Short Guiro"},
    {'P',   0,   0,  74, "GM1 Percussion", "Long Guiro"},
    {'P',   0,   0,  75, "GM1 Percussion", "Claves"},
    {'P',   0,   0,  76, "GM1 Percussion", "Hi Wood Block"},
    {'P',   0,   0,  77, "GM1 Percussion", "Low Wood Block"},
    {'P',   0,   0,  78, "GM1 Percussion", "Mute Cuica"},
    {'P',   0,   0,  79, "GM1 Percussion", "Open Cuica"},
    {'P',   0,   0,  80, "GM1 Percussion", "Mute Triangle"},
    {'P',   0,   0,  81, "GM1 Percussion", "Open Triangle"},
    {'P',   0,   0,  27, "GM Percussion Fallback", "High Q"},
    {'P',   0,   0,  28, "GM Percussion Fallback", "Slap"},
    {'P',   0,   0,  29, "GM Percussion Fallback", "Scratch Push"},
    {'P',   0,   0,  30, "GM Percussion Fallback", "Scratch Pull"},
    {'P',   0,   0,  31, "GM Percussion Fallback", "Sticks"},
    {'P',   0,   0,  32, "GM Percussion Fallback", "Square Click"},
    {'P',   0,   0,  33, "GM Percussion Fallback", "Metronome Click"},
    {'P',   0,   0,  34, "GM Percussion Fallback", "Metronome Bell"},
    {'P',   0,   0,  82, "GM Percussion Fallback", "Shaker"},
    {'P',   0,   0,  83, "GM Percussion Fallback", "Jingle Bell"},
    {'P',   0,   0,  84, "GM Percussion Fallback", "Bell Tree"},
    {'P',   0,   0,  85, "GM Percussion Fallback", "Castanets"},
    {'P',   0,   0,  86, "GM Percussion Fallback", "Mute Surdo"},
    {'P',   0,   0,  87, "GM Percussion Fallback", "Open Surdo"},
}; 
